### PR TITLE
fixed ResourceConflictException when Uploading

### PR DESCRIPTION
**Pull request by rriifftt**
when I Upload My Function to Lambda, following Exception Occured.

```
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:region:account_id:function:my_function
```

This may be due to a change in the lambda specification.
https://aws.amazon.com/jp/blogs/compute/tracking-the-state-of-lambda-functions/

so I Trying to fix this issue. Just Added `waiter` for `upload.py`.
Please Review this 🙏

### CODE REVIEW

**Comment by rriifftt** [comment]
@jarosser06 No longer under maintenance?

**Comment by RyPoints** [comment]
I also see this error, but Rift's version didn't fix it.

**Review by odeckmyn — APPROVED** [review]

**Comment by rriifftt** [comment]
@RyPoints same exception occurd? 
me and my colleagues could avoided that exception by this version..

**Comment by odeckmyn** [comment]
> @RyPoints same exception occurd?
> me and my colleagues could avoided that exception by this version..

Had another issue in my use case. Check my PR, I've reused your brilliant `wait` code for the `publish` action that was broken for me.

**Comment by gdelvalle** [comment]
closing in favor of #170

**Pull request closed without merging**
