### PR TITLE
Add environment variable support

### LINKED ISSUE #116: Support Environment variables
AWS has added support for configuring environment variables that will be set at runtime.

http://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html

### PR DESCRIPTION
**Pull request by brandond**
See:
http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.create_function
http://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html
re-fixes #116

### CODE REVIEW

**Comment by jarosser06** [comment]
I pulled this branch down locally and even with the new version of boto3 it still doesn't appear to work.

```shell
λ pip list | grep boto3
boto3 (1.4.1)

λ lambda-uploader

λ Building Package
λ Uploading Package
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/Users/jim/Projects/lambda-uploader/lambda_uploader/shell.py", line 179, in main
    _execute(args)
  File "/Users/jim/Projects/lambda-uploader/lambda_uploader/shell.py", line 94, in _execute
    upldr.upload(pkg)
  File "/Users/jim/Projects/lambda-uploader/lambda_uploader/uploader.py", line 142, in upload
    self.version = self.upload_new(pkg)
  File "/Users/jim/Projects/lambda-uploader/lambda_uploader/uploader.py", line 119, in upload_new
    Environment=environment,
  File "/Users/jim/.virtualenvs/lambda-uploader/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jim/.virtualenvs/lambda-uploader/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/jim/.virtualenvs/lambda-uploader/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/jim/.virtualenvs/lambda-uploader/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Environment", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig
```

**Comment by brandond** [comment]
Interesting, it appears that boto3 1.4.1 has an undeclared dependency on botocore>=1.4.76 for the updated service models (botocore/data/lambda/2015-03-31/service-2.json in particular).

**Comment by zkanda** [comment]
Any chance we merge and release this? :+1:

**Comment by brandond** [comment]
@zkanda not sure what the hold-up is either.

**Comment by brandond** [comment]
Also, I'ma at Re:Invent now, there's going to be a shit-ton of new stuff coming out requiring new service models anyway - might as well update for that.

**Comment by jarosser06** [comment]
I didn't have time to re-test it until this morning. Looks like it works as expected.

**Pull request merged**
