### PR TITLE
update boto3 version

### PR DESCRIPTION
**Pull request by wanghaven**
addresses #72

### CODE REVIEW

**Comment by jarosser06** [comment]
I don't see any issue with this but could you update the setup.py as well. https://github.com/rackerlabs/lambda-uploader/blob/master/setup.py#L8

**Comment by wanghaven** [comment]
@jarosser06 Good catch, can I go ahead and also bump the version to 0.5.2?

**Comment by jarosser06** [comment]
At this point we are pushing everything for a v1.0.0. We expect to drop a release in the next month.

**Comment by jarosser06** [comment]
Thanks for the submission.

**Pull request merged**
