### PR TITLE
Add environment variable support

### LINKED ISSUE #116: Support Environment variables
AWS has added support for configuring environment variables that will be set at runtime.

http://docs.aws.amazon.com/lambda/latest/dg/API_Environment.html

### PR DESCRIPTION
**Pull request by brandond**
Fixes #116

### CODE REVIEW

**Comment by jarosser06** [comment]
@brandond Can you rebase this off master it should fix the failing check.

**Comment by brandond** [comment]
@jarosser06 Done, looks good

**Comment by jarosser06** [comment]
Thanks looks good.

**Comment by MoOmEeN** [comment]
after merging this uploading fails for me with error:
`Unknown parameter in input: "Environment", must be one of: FunctionName, Role, Handler, Description, Timeout, MemorySize, VpcConfig, Runtime`

**Comment by jarosser06** [comment]
Yeah @MoOmEeN I see the same thing you do. @brandond Did this actually work for you? Environment doesn't appear to exist as a valid argument on that method. I'm going to revert this in the meantime since master is now broken.

**Comment by jarosser06** [comment]
Alright I just looked, this new argument is in boto3 latest but not yet in stable. Once this lands into boto3 stable we can get this feature added into the lambda-uploader. 

My apologies everyone for not digging into this as much as I should have. @brandond feel free to re-open this PR and we can merge once this once the Environments feature is available in boto3 stable.

**Comment by brandond** [comment]
My mistake, I just pulled the latest boto3 (1.4.1) from pip and it was in there. Wasn't aware that you wanted to stick with a particular branch.

**Pull request merged**
