### PR TITLE
Fixed issue with updating lambda configurations

### PR DESCRIPTION
**Pull request by quiver**
When updating existing lambda functions, only code was updated, that is,
only `update-function-code` API was called.

I have changed to call `update-function-configuration` and update the configuration.

### CODE REVIEW

**Comment by quiver** [comment]
Circle CI error message seems to be irrelevant with the PR code change.

> zipimport.ZipImportError: bad local file header in /home/ubuntu/virtualenvs/venv-2.7/lib/python2.7/site-packages/lambda_uploader-0.1.1-py2.7.egg Action failed: python setup.py install

**Comment by jarosser06** [comment]
I kicked it off again its the cache that kills the test :disappointed: .  I need to figure out a way to permanently fix that.

**Comment by jarosser06** [comment]
@quiver It looks like there is an extra blank line that flake8 is complaining about.  If you wouldn't mind getting that fixed I will go ahead and merge the PR :smile:

**Comment by quiver** [comment]
> @quiver It looks like there is an extra blank line that flake8 is complaining about. If you wouldn't mind getting that fixed I will go ahead and merge the PR

Fixed flake8 warning.  Sorry about that.

I ran tests locally and passed all tests.
```
$ flake8 .
$ py.test
========================================================================== test session starts ==========================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/ec2-user/lambda-uploader, inifile: tox.ini
collected 7 items

test/test_package.py .....
test/test_utils.py ..

======================================================================= 7 passed in 2.61 seconds ========================================================================
```
But again, zipimport error occurred at circle ci  :worried:

**Comment by jarosser06** [comment]
No worries I cleared the cache and the tests passed!  Thanks for the PR

**Pull request merged**
